[bitnami/*] Skip image's tag in the README files of the Bitnami Charts
Signed-off-by: Jota Martos <jotamartos@vmware.com>

diff --git a/.github/workflows/generate-chart-readme.yml b/.github/workflows/generate-chart-readme.yml
--- a/.github/workflows/generate-chart-readme.yml
+++ b/.github/workflows/generate-chart-readme.yml
@@ -31,12 +31,19 @@ jobs:
           DIFF_URL: "${{github.event.pull_request.diff_url}}"
           TEMP_FILE: "${{runner.temp}}/pr-${{github.event.number}}.diff"
         run: |
+          exit_code=0
           # This request doesn't consume API calls.
           curl -Lkso $TEMP_FILE $DIFF_URL
           files_changed="$(sed -nr 's/[\-\+]{3} [ab]\/(.*)/\1/p' $TEMP_FILE | sort | uniq)"
           # Adding || true to avoid "Process exited with code 1" errors
           charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -o "bitnami/[^/]*" | sort | uniq || true)"
           for chart in ${charts_dirs_changed}; do
+            echo "Validating README.md for ${chart}"
+            grep --quiet --extended-regexp "@param\s+\w*image.tag" "charts/${chart}/values.yaml" || exit_code=$?
+            if [[ $exit_code -ne 0 ]]; then
+              echo "::error:: Please ensure all image.tag params are skipped (@skip) in the charts/${chart}/values.yaml file"
+              exit "$exit_code"
+            fi
             echo "Updating README.md for ${chart}"
             readme-generator --values "charts/${chart}/values.yaml" --readme "charts/${chart}/README.md" --schema "/tmp/schema.json"
           done
